import React from 'react';
import PropTypes from 'prop-types';

/**
 * A flag is used to represent a political state.
 */
// eslint-disable-next-line import/prefer-default-export
export function Flag({
  // eslint-disable-next-line no-unused-vars,no-shadow,react/prop-types
  country, ...props
}) {
  return (

    // eslint-disable-next-line max-len
    // eslint-disable-next-line global-require,import/no-unresolved,import/no-dynamic-require,jsx-a11y/alt-text
    <img src={require(`./flags/${country}.png`)} alt={country} />

  );
}

Flag.propTypes = {
  /**
   * Country Flag
   */
  // eslint-disable-next-line react/require-default-props
  country: PropTypes.oneOf(
    ['Afghanistan',
      'Albania',
      'Algeria',
      'Andorra',
      'Angola',
      'Anguilla',
      'Antarctica',
      'Argentina',
      'Armenia',
      'Aruba',
      'Australia',
      'Austria',
      'Azerbaijan',
      'Bahrain',
      'Bangladesh',
      'Barbados',
      'Belarus',
      'Belgium',
      'Belize',
      'Benin',
      'Bermuda',
      'Bhutan',
      'Botswana',
      'Brazil',
      'Bulgaria',
      'Burundi',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Chad',
      'Chile',
      'China',
      'Colombia',
      'Croatia',
      'Cuba',
      'Curaçao',
      'Cyprus',
      'Czechia',
      'Denmark',
      'Djibouti',
      'Dominica',
      'Ecuador',
      'Egypt',
      'Eritrea',
      'Estonia',
      'Eswatini',
      'Ethiopia',
      'Fiji',
      'Finland',
      'France',
      'Gabon',
      'Georgia',
      'Germany',
      'Ghana',
      'Gibraltar',
      'Greece',
      'Greenland',
      'Grenada',
      'Guadeloupe',
      'Guam',
      'Guatemala',
      'Guernsey',
      'Guinea',
      'Guyana',
      'Haiti',
      'Honduras',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iraq',
      'Ireland',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'Jersey',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kiribati',
      'Kuwait',
      'Kyrgyzstan',
      'Latvia',
      'Lebanon',
      'Lesotho',
      'Liberia',
      'Libya',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Macao',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'Maldives',
      'Mali',
      'Malta',
      'Martinique',
      'Mauritania',
      'Mauritius',
      'Mayotte',
      'Mexico',
      'Monaco',
      'Mongolia',
      'Montenegro',
      'Montserrat',
      'Morocco',
      'Mozambique',
      'Myanmar',
      'Namibia',
      'Nauru',
      'Nepal',
      'Nicaragua',
      'Nigeria',
      'Niue',
      'Norway',
      'Oman',
      'Pakistan',
      'Palau',
      'Panama',
      'Paraguay',
      'Peru',
      'Pitcairn',
      'Poland',
      'Portugal',
      'Qatar',
      'Romania',
      'Rwanda',
      'Senegal',
      'Serbia',
      'Seychelles',
      'Singapore',
      'Slovakia',
      'Slovenia',
      'Somalia',
      'Spain',
      'Suriname',
      'Sweden',
      'Switzerland',
      'Taiwan',
      'Tajikistan',
      'Thailand',
      'Togo',
      'Tokelau',
      'Tonga',
      'Tunisia',
      'Turkey',
      'Turkmenistan',
      'Tuvalu',
      'Uganda',
      'Ukraine',
      'Uruguay',
      'Uzbekistan',
      'Vanuatu',
      'Venezuela',
      'Yemen',
      'Zambia',
      'Zimbabwe'],
  ).isRequired,
};
